[package]
name = "simple-hex"
version = "0.1.0"
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]
categories = ["no-std"]
keywords = ["ascii", "hex"]
license = "0BSD"
repository = "https://github.com/thenewwazoo/simple-hex"
description = "A simple ASCII hex-to-bytes-and-back library"
